### ISSUE TITLE
error opening connection, websocket: close 4004: Authentication failed.

### ISSUE THREAD

**Issue by MrLegiongame** [chelovek/discord-vk-bot#1]
Hi , I use visual studio code on windows 10 . 
I have a problem with your bot , when I run hem , I got an error : 
`failed to rotate: failed to create new symlink: symlink .\logs\bot.log.201803220200 ./logs/bot.log.201803220200_symlink: A required privilege is not held by the client.
?[36mINFO?[0m[0000] Bot starting ...
?[31mERRO?[0m[0000] error opening connection, websocket: close 4004: Authentication failed.`
what can I do to fix it ?

**Comment by qdron** [comment]
Try to specify the path to the logs. Pass your path in the "log" parameter when starting the bot. The path to the logs by default, it is set for Linux systems. Then I will correct that worked under Windows too.

**Comment by qdron** [comment]
I am added Readme in english
